import time

print("Welcome to the Deadly Escape.")
time.sleep(3)
print("Your mission is to escape this place ALIVE!.")
time.sleep(3)
print("You wake up in a bed fully clothed with no memory of how you got there or where you are. The room is square with no other furniture and has dark brown walls and one large dirty window.")
time.sleep(3)
print("You look around. You don\'t recognise anything and you have no personal posessions in the room. ")
time.sleep(3)
print("You climb out of bed. What do you want to do first? ")
time.sleep(3)
choice1 = input('Head over to the DOOR by typing "door", or move towards the WINDOW by typing "window". \n').lower()

if choice1 == "door":
    print("As you grab the door handle you noticed that it was ice cold, so cold infact that it gives you goosebumps.")
    time.sleep(3)
    print("You pull firmly but the door is heavy and sticky like there is a force pulling on the other side. The door opens slowly with a loud and rusty creeking noise.")
    time.sleep(3)
    print("As the door opens, it reveales a long dim lighted hallway.")  
else:
    print("You head over to the window, it is locked and at closer inspection the glass is fireproof glass and therefore unbreakable.")
    time.sleep(3)
    print("Outside of the window is pure blackness, no sky, no trees, no buildings and no lights of any kind.")
    time.sleep(3)
    print("All that is visible to you is your own reflection in the glass.")
    time.sleep(3)
    print("SUDDENLY !! there is a growling noise right next to your ear that makes the hairs on your neck stick up and your heart to race.")
    time.sleep(3)
    print("In a panic you look around. You see nothing useful, You look for a phone with no luck. Your only option is to use the door.")
    time.sleep(3)
    print("You move slowly towards the door.")
    time.sleep(3)
    print("As you grab the door handle you noticed that it was ice cold, so cold that it gave you goosebumps.")
    time.sleep(3)
    print("You pull firmly but the door is heavy and sticky like there is a force pulling on the other side. The door opens with a loud and rusty creaking noise.")
    time.sleep(3)
    print("As the door opens, it reveales a long dim lighted hallway.")

time.sleep(3)
print("You poke your head out looking left and right down the hallway but are unable to see the end of either corridor. With hesitance you step out into the hallway and you hear a loud high pitch scream seemingly coming from everywhere.")
time.sleep(3)
print("You turn to run back into the room but the heavy door slams closed behind you with a deafening thud!")
time.sleep(3)
print("Everything is silent for a few moments, then you hear what sounds like gears moving in the walls. You place your ear against the wall to hear better but when you do, the gears stop for a few seconds then there is a very loud mechanical CLICK! ")
time.sleep(3)
print("The lights that are dimmly lighting the hallway start to turn off systematiclly. As you look down the hallway in both direction's, the lights in the distance turn off, placing the corridor in darkness and that darkness is moving towards you.")
time.sleep(3)
print("With each light that goes out as it moves towards you, gets faster and faster")

choice2 = input('What do you do ??, type "left" to run down the left corridor. Type "right" to run down the right corridor. \n').lower()

if choice2 == "left":
    print("As your adrenaline kicks in, you sprint off down the corridor, struggling to breath.")
    time.sleep(3)
    print("As you run, all sounds fall into complete silence which causes you to stop running and listen intently. After a few seconds you begin to hear whispers, growling, snarling and howling.")
    time.sleep(3)
    print("You start to run again, stubbling over your own feet. Your crying and struggling to breath. You see a dimly light green sign hanging from the ceiling about 100 feet in front of you. The sign reads 'FIRE EXIT'.")
    time.sleep(3)
    print("As you come to the end of the corridor, everything is in complete darkness and the only light is from the sign above you")
    
else:
    print("As the darkness approaches you, your frozen in place with fear. As the last light goes out and you stand in complete darkness for a few seconds then the emergency lights kick in illuminating the corridor in a dim misty red hue.")
    time.sleep(3)
    print("you hear breathing right behind you, which makes your heartbeat faster than you have ever felt it beat in your life.")
    time.sleep(3)
    print("Then you feel a hand slowly squeeze your left shoulder, as you turn to look at the hand")
    time.sleep(3)
    print("you see its green and boney with thick hairs and boils covering it, the fingers are long and the nails are rotten and razor sharp")
    time.sleep(3)
    print("You try to run but the hand picks you up crushing the bones in your shoulder, now suspended in mid air, you start screaming for help .... 'HELP! HELP!'")
    time.sleep(3)
    print("As you struggle, more hands fire out of the darkness grabbing all four of your limbs. You struggle with no success") 
    time.sleep(3)
    print("The breathing you heard behind you stops and there is a whisper 'This is really going to hurt!' followed by a deep, echoing, demonic laughter 'HAHAHAHAHA!!'")
    time.sleep(3)
    print("Suddenly your limbs get ripped from your body. As your torso falls to the floor with a deafing thud. Blood leaking from the mouth and eyes, leaving a pool on the floor. Your body then gets dragged into the darkness in the blink of an eye where giggling can be heard and the consumption of flesh. ")
    time.sleep(3)
    print("Sorry my friend but you died so GAME OVER!")
    time.sleep(10)
    exit()

time.sleep(3)
print("As you stop at the end of the corridor, trying to catch your breath and looking for a way out.")
time.sleep(3)
print("you see the fire exit door, you attempt to open it but its locked. You throw your whole body against it hoping it would open but it didn't move an inch.")
time.sleep(3)
print("All growling and snarling you heard earlier has stopped, the corridor is dead silent, you suddenly hear machines winding up then the emergency lights come on. it fills the corridor with a dim misty red hue.")
time.sleep(3)
print("You look down the corridor and see a blurry figure in the distance, in your panic as you continue to look for a way out, The figure seems to be getting slowly closer and closer. As you bang on the fire exit door and the walls looking for a way out, the bone chilling sounds you heard earlier start again and slowly get louder.")
time.sleep(3)
print("You hear a loud creaking noice, as you spin around, you see that the fire exit is wide open. You look over your shoulder at the figure to see it is only a few feet away. Its hand stretched out towards you and its fingers spread as it tries to grab you.")
time.sleep(3)
print("You let out a little scream ... AHHHHH!, then run though the door slaming it behind you. As you lean against the door, breathing heavly.")
time.sleep(3)
print("As you look around the room your in, you notice that your standing in a lobby and the lighting in here is normal. You can only see two doors in front of you. one is a pair of large lift doors and the other is a door to a stairwell. You have to keep moving .... Which way do you choose ?.")
time.sleep(3)

choice3 = input("Type 'lift' to take the lift or type 'door' to use the stairwell. \n").lower()

if choice3 == "lift":
    print("You stubble upto the lift doors, and start button bashing the 'call lift button' in a panic. You continually look around, looking at every dark corner as you wait.")
    time.sleep(3)
    print("DING! .. As the lift arrives on your floor, The doors open slowly to show a very well lit and luxury interior. The walls were all wood paneling and a mirror fully covers the back wall.")
    time.sleep(3)
    print("You slowly and cautiously move into the lift. There is a panel of buttons with fancy fonts written on them ranging from ground to 8th floor. You look around to see to see if there is a indication of the floor your on but there isn't any, so you just push the ground floor button.")
    time.sleep(3)
    print("As the button lights up, the doors of the lift slam shut and a very happy and excited voice comes on over the speaker. 'HELLO LITTLE HUMAN!, YOU DIDN'T THINK IT WOULD BE THAT EASY, DID YOU!. TIME FOR A LITTLE PLAYTIME HAHAHAHHA!")
    time.sleep(3)
    print("Suddenly the lights in the lift start to flicker and there is banging on all sides of the lift, You hear screaming and chanting and glowling. You try and push the buttons on the panel but nothing is working.")
    time.sleep(3)
    print("You look in the mirror and there is a 8 foot skinny man standing behind you. The man's face and clothes are burnt and he is standing completely still staring into the mirror at you.")
    time.sleep(3)
    print("You spin around to look behind you, but there is nothing there. As you look back into the mirror the man is still there but now he has a smile on his face from ear to ear.")
    time.sleep(3)
    print("You breathing gets heavier, the lights begin to flicker faster. Then suddenly, the whole lift drops. As the lift is in free fall you try and grab onto something. Your stomoch has moved into your chest.")
    time.sleep(3)
    print("After falling from 8-10 seconds, the lift stops in an instant, slamming you into the floor with a skull crushing thud!. As you pick yourself up and look in the mirror.")
    time.sleep(3)
    print("You see that your covering in cuts and grazes, you have a large cut on your head and your covered in blood. You also realise that the man is gone, the noises are quiet although you have a slight ringing in your ear and the lighting has returned to normal.")
    time.sleep(3)
    print("With alot of hesitation, you slowly reach for the control panel and push the button for the ground floor again. You hear machine's turning on and parts moving in the wall.")
    time.sleep(3)
    print("Then there is a loud DING chime and the doors of the lift open slowly. The lift opens into a hotel lobby. From the lift you can see the front desk and some decoration's like pictures, plants and water fountain's. ")
    time.sleep(3)
    print("Everything looks normal so you pop your head out of the lift to see if the coast is clear. As you lean out, the doors of the lift slam closed on your neck with the force that would crush a melon.")
    time.sleep(3)
    print("With the speed and power the doors slammed shut, your body in the lift falls to the floor like a sack of potatoes and you head stay's in the door for a few seconds before sliding down the mirror door leaving a bloody trail behind it.")
    time.sleep(3)
    print("You failed your escape and lost your soul to the demons of this hotel. GAME OVER !!")
    exit()
else:
    print("You run straight into the stairway door in a panic, its locked so you come to quick stop as you smash into the soild door and fall to the floor. You bumped your head causing a big cut and alot of blood.")
    time.sleep(3)
    print("As you search for a handle or some way to open the door, you hear distinct laughing, as you slowly turn your head, fear fills your heart.")
    time.sleep(3)
    print("Standing at the door you just came through is a tall skinny man, his skin is all burnt and he is smiling ear to ear. He starts to move towards you.")
    time.sleep(3)
    print("You realise he is moving very smoothly, You look at his feet and see that he is floating about a foot above the ground. You suddenly get a chill up your spine. You start banging on the door as you panic and scream.")
    time.sleep(3)
    print("The door doesn't budge. You wipe away the tears that are running down your face. You stand up, inhale deeply and run towards the man, letting out a warcry!.")
    time.sleep(3)
    print("As you reach the man, his face changes from a smile to a frown. The man lets out a penatrating scream, then grabs you around the throat. Stopping you in your tracks. Crushing your windpipe.")
    time.sleep(3)
    print("The man walks forward a few steps with you hanging from his hand pulling you in closer to his face, looking you dead in the eye without blinking. The man breaths heavily on you, the smell was intolerable, smelling of rotten eggs and smoke and ash.")
    time.sleep(3)
    print("The man opens his mouth again and again let out a scream that makes your ears bleed. You look into his mouth and see that he has four rows of very sharp and bloody teeth.")
    time.sleep(3)
    print("After the screaming stops, the man lets out a very wide and mischieves smile. Then throws your weak and limp body through the locked door, hitting it so hard, the door is ripped off its hinges.")
    time.sleep(3)
    
print("")
time.sleep(3)
print("")
time.sleep(3)
print("")
time.sleep(3)
print("")
time.sleep(3)
print("")
time.sleep(3)
print("")
time.sleep(3)
print("")
time.sleep(3)
        











